server:
  port: 443
  ssl:
    #证书路径
    key-store: /Users/shensi/Keys/keystore.p12
    #密钥库密码
    key-store-password: 123456
    #密钥库类型
    key-store-type: PKCS12
    #密钥库别名
    key-alias: proxy-server
    client-auth: want